### ISSUE TITLE
worker dies unexpectedly

### ISSUE THREAD

**Issue by pulkitsinghal** [ShoppinPal/dolaterio#16]
These are the logs:

```
$ docker-compose logs --follow worker
Attaching to dolaterio_worker_1
worker_1     | panic: runtime error: invalid memory address or nil pointer dereference
worker_1     | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x45ed75]
worker_1     | 
worker_1     | goroutine 84 [running]:
worker_1     | panic(0x8bb960, 0xc42000a030)
worker_1     |  /usr/local/go/src/runtime/panic.go:500 +0x1a1
worker_1     | github.com/shoppinpal/dolaterio/docker.(*Engine).BuildContainer(0xc4201bca60, 0xc4201d2700, 0x0, 0x0, 0x0)
worker_1     |  /root/work/src/github.com/shoppinpal/dolaterio/docker/engine.go:70 +0xe65
worker_1     | github.com/shoppinpal/dolaterio/runner.Run(0xc4201d2700, 0xc4201bca60, 0x0, 0x0)
worker_1     |  /root/work/src/github.com/shoppinpal/dolaterio/runner/run.go:26 +0x82
worker_1     | github.com/shoppinpal/dolaterio/runner.(*JobRunner).run(0xc42014b220)
worker_1     |  /root/work/src/github.com/shoppinpal/dolaterio/runner/job_runner.go:99 +0x110
worker_1     | created by github.com/shoppinpal/dolaterio/runner.(*JobRunner).Start
worker_1     |  /root/work/src/github.com/shoppinpal/dolaterio/runner/job_runner.go:52 +0x4f
dolaterio_worker_1 exited with code 2
```

This is how I attempted to run the worker

```
echo "setup worker - with dolaterio AND autoset the WORKER_NAME in env vars" && \
export WORKER_NAME="shoppinpal_generate-weekly-stock-orders" && \
export IMAGE_NAME="shoppinpal/generate-weekly-stock-orders" && \
echo "WORKER_NAME: " $WORKER_NAME && \
echo "IMAGE_NAME: " $IMAGE_NAME && \
  curl localhost:7000/v1/workers \
    -H "Content-Type: application/json" \
    -X POST \
    -d '{
      "docker_image": "'"$IMAGE_NAME"'",
      "env": {"NODE_ENV": "local"},
      "worker_name": "'"$WORKER_NAME"'"
    }' && \
echo -e "\n You can check worker status with: \n curl localhost:7000/v1/workers/$WORKER_NAME \n" && \
echo "queue payload - with dolaterio AND autoset the JOB_ID in env vars" && \
export JOB_ID=$(
  curl localhost:7000/v1/jobs \
    -H "Content-Type: application/json" \
    -X POST \
    -d '{
      "worker_id": "'"$WORKER_NAME"'",
      "stdin": {
        "projectId": "xxx",
        "oauthToken": "yyy",
        "workerPayloads": []
      }
    }' | python -c 'import sys, json; print json.load(sys.stdin)["id"]'
) && echo $JOB_ID && \
echo -e "\n You can retrieve task/job status and results with: \n curl localhost:7000/v1/jobs/$JOB_ID \n" && \
curl localhost:7000/v1/jobs/$JOB_ID
```

This is great for catching onto problems but eventually we would want to always restart the worker service.

**Comment by harshadyeola** [comment]
@pulkitsinghal 

> This is great for catching onto problems but eventually we would want to always restart the worker service.

This can be accomplished via docker-compose file option.
